[firebase]
type = "service_account"
project_id = "edututor-ai-370b5"
private_key_id = "77fb1415b2acda0abc0cb003addc77990f62de9e"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCyvADyWYFIdmpt
ciFexH7NXw4teJ0IrFu+PYcuXu0LWiZ+QiCeuufBTDmkUanwRmlBtMRhZbV4hEWH
w3S4LxuY2hUiueC0gokrj06xrIPJVtYwqbw8qWyzsmPG5herRmpSSUW+6rUrUqip
Du0l64Sr/QYvkA86Z6uKlcLuafKVdfwfD2s5XQixQFQheD4EY5+AdKXWKhsQydio
LHp2NsEObSrnq2xnRdsCkGRpsFov0KArbe83wuDE7HjcNEefS1x4U9LFoz1oPk2y
Dz9h9PhqD/K/RYTMuhSU1jaKQd4ISYCt+4ZNHuPR7ssJqSLcRZnnSErrAcc3qKv2
l+5Fi0dHAgMBAAECggEATu1nq52r0iB8ogUWyF8UMcPKonjTO6vFPa60/dysZ+lw
+ytfdUjLI9hx0ebAGRs2yu21FN+Rsf0TKT8+UUF4OdkAIVwc5wmH4mT/1sT8U1JV
9ppVxiH5HydlGUWtaRSIyfqSYpsJ0u5HDZTKU4b8COkMrL88gkmafnHg6WB+39HD
SkG3xGlLZ+448z1hcdygjszjHd7QMHTYmwgsqA98k4uBzAeh+8JsmWvTJ3CaoUYH
kNLSGXCweYNXyNEtupL/mTVvSvl3cJs/m+LtrPNBf6+GTGrt3kTAHuRRHJkxvgAV
EIzRSOH3PEK8rGQb3cvB0zN5eEKmbrXTeiCQVDtEiQKBgQDmWjloOQ8twtpcS+Nt
SLkH4a5yRLPI/KR5jLfDogLdMI6CXQQmufIIElVX9sSSdI0B2A53QdNNfCdgxJwr
Bq67Oppakl5+83ORGOuFsJeGgcA0IS/PQTpoDApMAuLckav5JS3c56FTq3q7Lwg1
0mZs2oFjpWePIY12QQRQcma4OQKBgQDGooBOIHrdKa1Hb/nsxr2X90ERxnUl5XLz
1gp77E97sK9ckvkzhascSwPeRriUmY03ZeNXbHvcUBdjRUmDNFWmb6dpNAAcVLhV
7vOija+00S8iizuGzWO6Ek3WfC/5byInKK/IQwneYUBPf3mpb5VYDukamyTf0OUc
r2OAIab7fwKBgQDISyFpj1u0ZZ5q7I2nI7nHsaN2tmhBVfRJwGK1F7U30RXJIsoO
Rla+T/qnTumjkvZc6RnC9pid4lt3F93Wx6u9HvrB0E2cQ2F0g9+e0mseyMlwSn8A
zm3TtMxrRYMvWPbY30wercWoNA22nvGbowPumJwzIcqHORyA+42dyaupeQKBgQCw
zOFBKP3TLw5x4IRnMTp+MfDz/l41XfakfKaWSO8yXECqOJOhPV/hbg/CX9ZZRheA
8KqbHQ9eONeoX3qgUwvNeeJb7JIQpYPx0R+AV3bGjc7Tg3R3dwdGDpbDy4P0E+wl
SLy1lp4JFyzj1cYXfx9B4vuu19rJcKkNkDsTSGDVxwKBgQDl1ohv7zMMMC5AkcOv
rrv0wr9f+umU4bJ3yhxXU/e+ZfG17GCZQzIjQpF/JdcZIpCDtCTq6kR+Re4bbfNC
9BkK53VnAozppGzVhzVTClGyGab1ae+5OYeVn2vSiIzKZt1/0FCesPLNzyIiFmmo
IoA0s6TRrvEp5Gi4x+s/0xWY0A==
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-fbsvc@edututor-ai-370b5.iam.gserviceaccount.com"
client_id = "115363599127832903278"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40edututor-ai-370b5.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
